version: '3.8'

services:
  saphir-db:
    image: postgres:latest
    container_name: saphir-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5002:5432"
    volumes:
      - "C:/Users/ProBook 440 G8/db-vovlumes/saphir-db:/var/lib/postgresql/data"
    networks:
      - saphir

  saphir:
    build:
      context: .
      dockerfile: saphir/Dockerfile
    image: saphir:latest
    container_name: saphir
    environment:
      JWT_SECRET: hfqDNmNsBHr6firFI0Pw6USCVg+LonAV95kCMCL7UlUq19bmD/xCF+II2N1aQcy0c70GaSvByMnF+tiYiTknDg==
      SPRING_DATASOURCE_URL: jdbc:postgresql://saphir-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    depends_on:
      - saphir-db
    ports:
      - "8080:8080"
      - "4005:4005"
    networks:
      - saphir

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: api-gateway:latest
    container_name: api-gateway
    environment:
      SAPHIR_URL: "http://saphir:4005"
    ports:
      - "4003:4003"
    networks:
      - saphir
    depends_on:
      - saphir

networks:
  saphir:
    driver: bridge

volumes:
  db_data:
