logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG

server:
  port: 4003

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
              #Route to saphir
            - id: saphir-auth-route
#              uri: http://saphir.railway.internal:4005
              uri: http://saphir:4005
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

              #Route to log out
            - id: saphir-auth-logout
#              uri: http://saphir.railway.internal:4005
              uri: http://saphir:4005
              predicates:
                - Path=/api/logout
              filters:
                - StripPrefix=1


              # Route to offers
            - id: saphir-offer-route
#              uri: http://saphir.railway.internal:4005
              uri: http://saphir:4005
              predicates:
                - Path=/api/offers/**
              filters:
                - JwtValidation

            - id: saphir-user-route
#              uri: http://saphir.railway.internal:4005
              uri: http://saphir:4005
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=1


            - id: saphir-bundle-route
#              uri: http://saphir.railway.internal:4005
              uri: http://saphir:4005
              predicates:
                - Path=/api/bundles/**
              filters:
                - JwtValidation


            - id: api-docs-saphir-users-route
#              uri: http://saphir.railway.internal:4005
              uri: http://saphir:4005
              predicates:
                - Path=/api-docs/users
              filters:
                - RewritePath=/api-docs/users,/v3/api-docs


            - id: api-docs-saphir-auth-route
#              uri: http://saphir.railway.internal:4005
              uri: http://saphir:4005
              predicates:
                - Path=/api-docs/auth
              filters:
                - RewritePath=/api-docs/auth,/v3/api-docs

            - id: api-docs-saphir=offers-route
#              uri: http://saphir.railway.internal:4005
              uri: http://saphir:4005
              predicates:
                - Path=/api-docs/offers
              filters:
                - RewritePath=/api-docs/offers,/v3/api-docs








