### GET request to example server
@token =eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJ0ZXN0MkBob3RtYWlsLmNvbSIsImlhdCI6MTc1Mzc0NzUwMCwiZXhwIjoxNzUzODMzOTAwfQ.cgwa_bjT0PQfRAI39GwCgGfBDZSJnzVLqe4jZN5ZP6M
PATCH localhost:4003/api/bundles/1
Content-Type: application/json
Authorization: Bearer {{token}}

{

  "name": "Ponctuel C "

}
###